baseUrl = https://demo.reportportal.io/api/v1/
projectName = default_personal/
logging = true
token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTU1MjE4MjQsInVzZXJfbmFtZSI6ImRlZmF1bHQiLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoibnZPcVgxbDNHMlJQUG45ckhkN2JKYjdJTzVzIiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ.h_Pt7U9aes5AOsWWZfNmi8cnvucbspfJWM9SxOofHKE
