baseUrl = https://demo.reportportal.io/api/v1/
projectName = default_personal/
logging = true
token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTExMTMwNTgsInVzZXJfbmFtZSI6ImRlZmF1bHQiLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiR3BDd1F4TlVpY1l2Z0pGeFdMSGxvV3hEN0VJIiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ._kmf2wTYt1ZxdkBdooHNFt1F1EwHb95khTyyu1DQHtc