baseUrl = https://demo.reportportal.io/api/v1/
projectName = default_personal/
logging = true
token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTYwOTE1ODQsInVzZXJfbmFtZSI6ImRlZmF1bHQiLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoicVItZG1GOHl0MS1EaDAwSm9wMXNaTEZpUFRZIiwiY2xpZW50X2lkIjoidWkiLCJzY29wZSI6WyJ1aSJdfQ.7qNjP9mdc-UCfw86aqVDW813HbtkdJ1hoQt7bb2xgKw
